# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
stages:
  - build
  - test
  - sonar
  - docker
build:
  stage: build
  script:
    - ./gradlew assemble
test:
  stage: test
  script:
    - ./gradlew test

sonar:
  stage: sonar
  script:
    - ./gradlew test jacocoTestReport sonar

docker:
  stage: docker
  script:
    - ./gradlew assemble
    - docker build -t real-estate-project-backend .
    - docker stop real-estate-project-backend-staging
    - docker rm real-estate-project-backend-staging
    - docker start real_estate_project_db_staging
    - docker run -d -p 8090:8080 --net=real_estate_project_network_staging --env spring_profiles_active=staging --name=real-estate-project-backend-staging real-estate-project-backend
  only:
    - master